### PR TITLE
octets: fix macro parameter expansion inside unsafe block

### LINKED ISSUE #184: Macros in src/octet.rs may have unexpected unsafe behavior
https://github.com/cloudflare/quiche/blob/d646a60b497be4a92046fbd705161164388b73d2/src/octets.rs#L69-L73

https://github.com/cloudflare/quiche/blob/d646a60b497be4a92046fbd705161164388b73d2/src/octets.rs#L99-L103

These both evaluate some of their parameters in an `unsafe` block. This allows the callers of these macros to use an unsafe expression there, without needing to specify an `unsafe` block.

This is almost always unintended (and indeed, there's no comments suggesting it was intended). I'd suggest doing `let len = $len;` outside of the `unsafe` block to avoid this.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=578b803a28085939cd5a4791a4fb4dd4 is an example of how this can fail.

### PR DESCRIPTION
**Pull request by LPardue**
Fixes #184

### CODE REVIEW

File: src/octets.rs [hunk 1]
```diff
@@ -93,14 +94,16 @@ macro_rules! put_u {
...
         }
 
+        let len = $len;
+
         #[allow(clippy::range_plus_one)]
-        let dst = &mut $b.buf[$b.off..($b.off + $len)];
+        let dst = &mut $b.buf[$b.off..($b.off + len)];
 
         unsafe {
             let src = &<$ty>::to_be($v) as *const $ty as *const u8;
```
Comment (alex) [inline src/octets.rs]: You've also got `$v` in this macro, sorry I missed that on first review.

Comment (LPardue) [reply src/octets.rs]: Fixed! thanks.

File: src/octets.rs [hunk 2]
```diff
@@ -66,11 +66,12 @@ macro_rules! peek_u {
         }
 
         let mut out: $ty = 0;
+        let len = $len;
```
Comment (ghedo) [inline src/octets.rs]: It'd probably be nicer to put this above the `if src.len() < $len` (i.e. immediately before or after `let src = ...`) for consistency, so we would use `len` instead of `$len` everywhere.

File: src/octets.rs [hunk 3]
```diff
@@ -93,14 +94,17 @@ macro_rules! put_u {
             return Err(BufferTooShortError);
         }
 
+        let v = $v;
+        let len = $len;
```
Comment (ghedo) [inline src/octets.rs]: Same.

File: src/octets.rs (hunk 2 above)
Comment (LPardue) [reply src/octets.rs]: yeah I missed that, thanks.

Comment (ghedo) [reply src/octets.rs]: Updated.
