### PR TITLE
Fix 32bit x86 build

### LINKED ISSUE #277: Cross compiling fails
I'm running an amd64 system trying to cross compile for x86 (which is common for multilib).

Building quiche by running:
`cargo build --target=i686-unknown-linux-gnu`

results in this build failure:
```
   Compiling quiche v0.1.0 (/var/tmp/portage/net-libs/quiche-0.1.0/work/quiche-0.1.0-abi_x86_32.x86)
error: failed to run custom build command for `quiche v0.1.0 (/var/tmp/portage/net-libs/quiche-0.1.0/work/quiche-0.1.0-abi_x86_32.x86)`

Caused by:
  process didn't exit successfully: `/var/tmp/portage/net-libs/quiche-0.1.0/work/quiche-0.1.0-abi_x86_32.x86/target/release/build/quiche-0b547c5a4bcd114c/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/var/tmp/portage/net-libs/quiche-0.1.0/work/quiche-0.1.0-abi_x86_32.x86/deps/boringssl" "-DCMAKE_INSTALL_PREFIX=/var/tmp/portage/net-libs/quiche-0.1.0/work/quiche-0.1.0-abi_x86_32.x86/target/i686-unknown-linux-gnu/release/build/quiche-f20871fc80c099ad/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m32 -march=i686 -march=native -pipe -fuse-linker-plugin -flto -ftree-vectorize -ftree-slp-vectorize -falign-functions=32 -fgraphite-identity -floop-nest-optimize -fno-lto -fno-use-linker-plugin" "-DCMAKE_C_COMPILER=/usr/lib/ccache/bin/x86_64-pc-linux-gnu-gcc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m32 -march=i686 -march=native -pipe -fuse-linker-plugin -flto -ftree-vectorize -ftree-slp-vectorize -falign-functions=32 -fgraphite-identity -floop-nest-optimize -fno-lto -fno-use-linker-plugin" "-DCMAKE_CXX_COMPILER=/usr/lib/ccache/bin/x86_64-pc-linux-gnu-g++" "-DCMAKE_BUILD_TYPE=RelWithDebInfo"
```
[snip]
```
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: i386:x86-64 architecture of input file `../crypto/libcrypto.a(aesni-x86_64.S.o)' is incompatible with i386 output
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: i386:x86-64 architecture of input file `../crypto/libcrypto.a(aes-x86_64.S.o)' is incompatible with i386 output
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: i386:x86-64 architecture of input file `../crypto/libcrypto.a(ghash-x86_64.S.o)' is incompatible with i386 output
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: i386:x86-64 architecture of input file `../crypto/libcrypto.a(md5-x86_64.S.o)' is incompatible with i386 output
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: i386:x86-64 architecture of input file `../crypto/libcrypto.a(sha1-x86_64.S.o)' is incompatible with i386 output
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: i386:x86-64 architecture of input file `../crypto/libcrypto.a(sha256-x86_64.S.o)' is incompatible with i386 output
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: i386:x86-64 architecture of input file `../crypto/libcrypto.a(sha512-x86_64.S.o)' is incompatible with i386 output
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: i386:x86-64 architecture of input file `../crypto/libcrypto.a(vpaes-x86_64.S.o)' is incompatible with i386 output
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: i386:x86-64 architecture of input file `../crypto/libcrypto.a(x86_64-mont.S.o)' is incompatible with i386 output
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: i386:x86-64 architecture of input file `../crypto/libcrypto.a(chacha-x86_64.S.o)' is incompatible with i386 output
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: i386:x86-64 architecture of input file `../crypto/libcrypto.a(x86_64-mont5.S.o)' is incompatible with i386 output
```

Here's the full build log:
[net-libs:quiche-0.1.0:20191127-222131.log](https://github.com/cloudflare/quiche/files/3899719/net-libs.quiche-0.1.0.20191127-222131.log)

Regardless of the `--target` provided to `cargo`, quiche is always building boringssl for the native arch, not the target one.

Parameters need to be provided to the boringssl cmake build process so it builds for the cargo provided `--target` arch and not the native arch.

### PR DESCRIPTION
**Pull request by junhochoi**
Pass 32bit toolchain to cmake for cross-building x86 linux from
x86_64 linux. Also CI target is added.

Ref: https://github.com/google/boringssl/blob/master/BUILDING.md

Fixes #277

### CODE REVIEW

File: src/build.rs [hunk 1]
```diff
@@ -120,7 +121,20 @@ fn get_boringssl_cmake_config() -> cmake::Config {
             boringssl_cmake
         },
 
-        _ => boringssl_cmake,
+        _ => match arch.as_ref() {
+            // 32bit x86 build
```
Comment (ghedo) [inline src/build.rs]: This comment doesn't seem super useful.
```suggestion
```

File: .travis.yml [hunk 2]
```diff
@@ -139,6 +139,24 @@ matrix:
...
+     language: rust
+     rust: stable
+     env:
+       TARGET=i686-unknown-linux-gnu
+     before_install:
+      # Install and use the current stable release of Go
+      - gimme --list
+      - eval "$(gimme stable)"
+      - gimme --list
+      - rustup target add $TARGET || true
```
Comment (ghedo) [inline .travis.yml]: Why is `|| true` needed?

Also might want to add a comment here, like:
```suggestion
      # Install x86 Rust target for cross-building.
      - rustup target add $TARGET || true
```

File: src/build.rs [hunk 3]
```diff
@@ -120,7 +121,20 @@ fn get_boringssl_cmake_config() -> cmake::Config {
             boringssl_cmake
         },
 
-        _ => boringssl_cmake,
+        _ => match arch.as_ref() {
```
Comment (ghedo) [inline src/build.rs]: Why do you need a match here? In the `_` case you can just do:
```rust
        _ =>  {
            // Configure BoringSSL for building on 32-bit platforms.
            if arch == "x86" {
                boringssl_cmake.define(
                    "CMAKE_TOOLCHAIN_FILE",
                    pwd.join("deps/boringssl/util/32-bit-toolchain.cmake")
                        .as_os_str(),
                );
            }

            boringssl_cmake
        },
```

File: .travis.yml [hunk 4]
```diff
@@ -139,6 +139,24 @@ matrix:
       - tools/setup_android.sh
      script:
       - tools/build_android.sh --release --verbose
+   - name: "Cross build x86 from x86_64"
```
Comment (ghedo) [inline .travis.yml]: Better shorten this, otherwise it won't fit in the Travis CI UI.
```suggestion
   - name: "x86 cross-build"
```

**Comment by ghedo** [comment]
To speed-up merging I addressed the comments myself, we can undo the changes later if needed.

**Comment by junhochoi** [comment]
Thanks. Looks like it broke CI which is not caugut on the branch. Created #289 to fix it.
