### PR TITLE
examples: handle socket.send() result

### LINKED ISSUE #56: http3-server example on native windows build
Running latest master on Windows, I find that the http3-server.rs example crashes when doing a simple test on 127.0.01. The backtrace points at the line `socket.send_to(&out[..write], &peer).unwrap();`

@RReverser did you ever try quiche natively on Windows?

```
C:\Users\lucas\dev\GitHub\quiche>"target/debug/examples/http3-server.exe" --listen 127.0.0.1:4433
[2019-06-01T21:45:54.254247500Z TRACE mio::poll] registering with poller
[2019-06-01T21:45:54.254509800Z TRACE mio::sys::windows::selector] register Token(0) Readable
[2019-06-01T21:45:54.255245800Z TRACE mio::sys::windows::selector] set readiness to (empty)
[2019-06-01T21:45:54.256242500Z TRACE mio::sys::windows::udp] scheduling a read
[2019-06-01T21:45:54.259233900Z TRACE mio::sys::windows::selector] select; timeout=None
[2019-06-01T21:45:54.259233900Z TRACE mio::sys::windows::selector] polling IOCP
[2019-06-01T21:45:56.720233000Z TRACE mio::sys::windows::selector] select; -> got overlapped
[2019-06-01T21:45:56.720233000Z TRACE mio::sys::windows::udp] finished a recv 1200
[2019-06-01T21:45:56.722211900Z TRACE mio::sys::windows::selector] set readiness to Readable
[2019-06-01T21:45:56.722211900Z TRACE mio::sys::windows::selector] returning
[2019-06-01T21:45:56.723394300Z TRACE mio::sys::windows::selector] set readiness to (empty)
[2019-06-01T21:45:56.724216400Z TRACE mio::sys::windows::udp] scheduling a read
[2019-06-01T21:45:56.734439100Z DEBUG http3_server] got 1200 bytes
[2019-06-01T21:45:56.735476100Z TRACE http3_server] got packet Initial version=babababa dcid=7db9b2ea15a41ae97c49562ff0b509cc scid=06641db5127f32f20fdf0b0369239fcd2a22 token=
[2019-06-01T21:45:56.736452700Z WARN  http3_server] Doing version negotiation
[2019-06-01T21:45:56.741790400Z TRACE mio::sys::windows::selector] set readiness to (empty)
[2019-06-01T21:45:56.750760200Z TRACE mio::sys::windows::udp] scheduling a send
[2019-06-01T21:45:56.757742200Z DEBUG http3_server] recv() would block
[2019-06-01T21:45:56.764726100Z TRACE mio::sys::windows::selector] select; timeout=None
[2019-06-01T21:45:56.766724700Z TRACE mio::sys::windows::selector] polling IOCP
[2019-06-01T21:45:56.772197100Z TRACE mio::sys::windows::selector] select; -> got overlapped
[2019-06-01T21:45:56.778186600Z TRACE mio::sys::windows::udp] finished a send 44
[2019-06-01T21:45:56.778186600Z TRACE mio::sys::windows::selector] set readiness to Writable
[2019-06-01T21:45:56.779177400Z TRACE mio::sys::windows::selector] returning
[2019-06-01T21:45:56.788179700Z DEBUG http3_server] timed out
[2019-06-01T21:45:56.789153500Z TRACE mio::sys::windows::selector] select; timeout=None
[2019-06-01T21:45:56.802886300Z TRACE mio::sys::windows::selector] polling IOCP
[2019-06-01T21:45:56.854628300Z TRACE mio::sys::windows::selector] select; -> got overlapped
[2019-06-01T21:45:56.855646000Z TRACE mio::sys::windows::udp] finished a recv 1200
[2019-06-01T21:45:56.860923200Z TRACE mio::sys::windows::selector] set readiness to Readable | Writable
[2019-06-01T21:45:56.861613000Z TRACE mio::sys::windows::selector] returning
[2019-06-01T21:45:56.861613000Z TRACE mio::sys::windows::selector] set readiness to Writable
[2019-06-01T21:45:56.862606600Z TRACE mio::sys::windows::udp] scheduling a read
[2019-06-01T21:45:56.863603700Z DEBUG http3_server] got 1200 bytes
[2019-06-01T21:45:56.864603200Z TRACE http3_server] got packet Initial version=ff000014 dcid=7db9b2ea15a41ae97c49562ff0b509cc scid=06641db5127f32f20fdf0b0369239fcd2a22 token=
[2019-06-01T21:45:56.874334000Z WARN  http3_server] Doing stateless retry
[2019-06-01T21:45:56.878450900Z TRACE mio::sys::windows::selector] set readiness to (empty)
[2019-06-01T21:45:56.880314800Z TRACE mio::sys::windows::udp] scheduling a send
[2019-06-01T21:45:56.887407000Z DEBUG http3_server] recv() would block
[2019-06-01T21:45:56.889291400Z TRACE mio::sys::windows::selector] select; timeout=None
[2019-06-01T21:45:56.891288400Z TRACE mio::sys::windows::selector] polling IOCP
[2019-06-01T21:45:56.901945600Z TRACE mio::sys::windows::selector] select; -> got overlapped
[2019-06-01T21:45:56.902942400Z TRACE mio::sys::windows::udp] finished a send 84
[2019-06-01T21:45:56.913543500Z TRACE mio::sys::windows::selector] set readiness to Writable
[2019-06-01T21:45:56.921259400Z TRACE mio::sys::windows::selector] returning
[2019-06-01T21:45:56.925885600Z DEBUG http3_server] timed out
[2019-06-01T21:45:56.928044600Z TRACE mio::sys::windows::selector] select; timeout=None
[2019-06-01T21:45:56.929041700Z TRACE mio::sys::windows::selector] polling IOCP
[2019-06-01T21:45:56.983124500Z TRACE mio::sys::windows::selector] select; -> got overlapped
[2019-06-01T21:45:56.983257200Z TRACE mio::sys::windows::udp] finished a recv 1200
[2019-06-01T21:45:56.988341300Z TRACE mio::sys::windows::selector] set readiness to Readable | Writable
[2019-06-01T21:45:56.989106500Z TRACE mio::sys::windows::selector] returning
[2019-06-01T21:45:56.989784000Z TRACE mio::sys::windows::selector] set readiness to Writable
[2019-06-01T21:45:56.990151900Z TRACE mio::sys::windows::udp] scheduling a read
[2019-06-01T21:45:57.000907400Z DEBUG http3_server] got 1200 bytes
[2019-06-01T21:45:57.003711900Z TRACE http3_server] got packet Initial version=ff000014 dcid=0fb4280f7fad9fd01e570195cf23022bc393 scid=06641db5127f32f20fdf0b0369239fcd2a22 token=7175696368657f0000017db9b2ea15a41ae97c49562ff0b509cc
[2019-06-01T21:45:57.013065000Z DEBUG http3_server] New connection: dcid=0fb4280f7fad9fd01e570195cf23022bc393 scid=0fb4280f7fad9fd01e570195cf23022bc393
[2019-06-01T21:45:57.015027700Z TRACE quiche] 0fb4280f7fad9fd01e570195cf23022bc393 rx pkt Initial version=ff000014 dcid=0fb4280f7fad9fd01e570195cf23022bc393 scid=06641db5127f32f20fdf0b0369239fcd2a22 token=7175696368657f0000017db9b2ea15a41ae97c49562ff0b509cc len=1129 pn=2
[2019-06-01T21:45:57.026211500Z TRACE quiche] 0fb4280f7fad9fd01e570195cf23022bc393 rx frm CRYPTO off=0 len=512
[2019-06-01T21:45:57.032249200Z TRACE quiche::tls] 0fb4280f7fad9fd01e570195cf23022bc393 tls write message lvl=Initial len=122
[2019-06-01T21:45:57.033212800Z TRACE quiche::tls] 0fb4280f7fad9fd01e570195cf23022bc393 tls set encryption secret lvl=Handshake
[2019-06-01T21:45:57.042167300Z TRACE quiche::tls] 0fb4280f7fad9fd01e570195cf23022bc393 tls set encryption secret lvl=Application
[2019-06-01T21:45:57.045617300Z TRACE quiche::tls] 0fb4280f7fad9fd01e570195cf23022bc393 tls write message lvl=Handshake len=1345
[2019-06-01T21:45:57.051590700Z TRACE quiche] 0fb4280f7fad9fd01e570195cf23022bc393 rx frm PADDING len=596
[2019-06-01T21:45:57.052729200Z DEBUG http3_server] 0fb4280f7fad9fd01e570195cf23022bc393 processed 1200 bytes
[2019-06-01T21:45:57.053584900Z DEBUG http3_server] recv() would block
[2019-06-01T21:45:57.054622000Z TRACE quiche] 0fb4280f7fad9fd01e570195cf23022bc393 tx pkt Initial version=ff000014 dcid=06641db5127f32f20fdf0b0369239fcd2a22 scid=0fb4280f7fad9fd01e570195cf23022bc393 len=148 pn=0
[2019-06-01T21:45:57.055582000Z TRACE quiche] 0fb4280f7fad9fd01e570195cf23022bc393 tx frm ACK delay=5076 blocks=[2..2][2019-06-01T21:45:57.056577100Z TRACE quiche] 0fb4280f7fad9fd01e570195cf23022bc393 tx frm CRYPTO off=0 len=122
[2019-06-01T21:45:57.057575500Z TRACE quiche::recovery] 0fb4280f7fad9fd01e570195cf23022bc393 timer=997.174123ms crypto=194 inflight=194 cwnd=14520 latest_rtt=0ns srtt=None min_rtt=0ns rttvar=0ns probes=0
[2019-06-01T21:45:57.058929700Z TRACE mio::sys::windows::selector] set readiness to (empty)
[2019-06-01T21:45:57.062562700Z TRACE mio::sys::windows::udp] scheduling a send
[2019-06-01T21:45:57.063558700Z DEBUG http3_server] 0fb4280f7fad9fd01e570195cf23022bc393 written 194 bytes
[2019-06-01T21:45:57.065556500Z TRACE quiche] 0fb4280f7fad9fd01e570195cf23022bc393 tx pkt Handshake version=ff000014 dcid=06641db5127f32f20fdf0b0369239fcd2a22 scid=0fb4280f7fad9fd01e570195cf23022bc393 len=1151 pn=0
[2019-06-01T21:45:57.067558700Z TRACE quiche] 0fb4280f7fad9fd01e570195cf23022bc393 tx frm CRYPTO off=0 len=1131
[2019-06-01T21:45:57.080512700Z TRACE quiche::recovery] 0fb4280f7fad9fd01e570195cf23022bc393 timer=985.608691ms crypto=1390 inflight=1390 cwnd=14520 latest_rtt=0ns srtt=None min_rtt=0ns rttvar=0ns probes=0
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Kind(WouldBlock)', src\libcore\result.rs:997:5stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\sys\windows\backtrace\mod.rs:95
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\sys\windows\backtrace\mod.rs:82
   2: std::sys_common::backtrace::_print
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::print
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\sys_common\backtrace.rs:59
   4: std::panicking::default_hook::{{closure}}
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:197
   5: std::panicking::default_hook
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:474
   7: std::panicking::continue_panic_fmt
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:381
   8: std::panicking::rust_begin_panic
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:308
   9: core::panicking::panic_fmt
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libcore\panicking.rs:85
  10: core::result::unwrap_failed<std::io::error::Error>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libcore\macros.rs:18
  11: core::result::Result<usize, std::io::error::Error>::unwrap<usize,std::io::error::Error>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libcore\result.rs:798
  12: http3_server::main
             at .\examples\http3-server.rs:336
  13: std::rt::lang_start::{{closure}}<()>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libstd\rt.rs:64
  14: std::rt::lang_start_internal::{{closure}}
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\rt.rs:49
  15: std::panicking::try::do_call<closure,i32>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:293
  16: panic_unwind::__rust_maybe_catch_panic
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libpanic_unwind\lib.rs:87
  17: std::panicking::try
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:272
  18: std::panic::catch_unwind
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panic.rs:388
  19: std::rt::lang_start_internal
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\rt.rs:48
  20: std::rt::lang_start<()>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libstd\rt.rs:64
  21: main
  22: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  23: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  24: BaseThreadInitThunk
  25: RtlUserThreadStart
```

### PR DESCRIPTION
**Pull request by LPardue**
fixes #56

All Rust examples changed to handle the result of socket.send[_to](). Tested local and remote interop of http3-client.

### CODE REVIEW

File: examples/client.rs [hunk 1]
```diff
@@ -140,7 +140,22 @@ fn main() {
         Err(e) => panic!("initial send failed: {:?}", e),
     };
 
-    socket.send(&out[..write]).unwrap();
+    loop {
```
Comment (ghedo) [inline examples/client.rs]: Since we don't really care about the `Ok` value, this can probably be simplified to something like:
```rust
while let Err(e) = socket.send(&out[..write]) {
    if e.kind() == std::io::ErrorKind::WouldBlock {
        debug!("send() would block");
        break;
    }

    panic!("send() failed: {:?}", e);
}
```

File: examples/client.rs [hunk 2]
```diff
@@ -140,7 +140,22 @@ fn main() {
...
+        match socket.send(&out[..write]) {
+            Ok(_) => {
+                // Sent ok, so move on
+                break;
+            },
+
+            Err(e) => {            
+                if e.kind() == std::io::ErrorKind::WouldBlock {
+                    debug!("send() would block");
```
Comment (ghedo) [inline examples/client.rs]: This would still panic btw, as there is no `break`.

File: examples/client.rs [hunk 3]
```diff
@@ -266,7 +281,19 @@ fn main() {
                 },
             };
 
-            socket.send(&out[..write]).unwrap();
+            match socket.send(&out[..write]) {
```
Comment (ghedo) [inline examples/client.rs]: Ditto, this (and the similar matches in the other examples) can be simplfiied as:
```rust
if let Err(e) = socket.send(&out[..write]) {
    if e.kind() == std::io::ErrorKind::WouldBlock {
        debug!("send() would block");
        break;
    }

    panic!("send() failed: {:?}", e);
}
```

File: examples/http3-client.rs [hunk 4]
```diff
@@ -315,7 +315,19 @@ fn main() {
                 },
             };
 
-            socket.send(&out[..write]).unwrap();
+            match socket.send(&out[..write]) {
```
Comment (ghedo) [inline examples/http3-client.rs]: Besides the simplification, you probably want to do the loop+match thing for the initial `socket.send()` call in this file like you did in `client.rs`

Comment (LPardue) [reply examples/http3-client.rs]: I shamelessly copied the socket read code which just breaks. Adding a loop-in-loop,I figured, might cause the socket reads (along with other things) to get blocked while trying to send. On windows, send() blocks quite often - at the start of a connection at least 5 iterations...

Comment (ghedo) [reply examples/http3-client.rs]: My comment wasn't very clear, but what I meant is that the first `socket.send()` call (the one that starts the connection) should also be changed and use a loop like you did in `client.rs`. That is the one on https://github.com/cloudflare/quiche/blob/master/examples/http3-client.rs#L148 The call linked to this comment should just get the `if let ...` simplification.

Comment (LPardue) [reply examples/http3-client.rs]: Got it, fixed.

File: examples/client.rs (hunk 3 above)
Comment (LPardue) [reply examples/client.rs]: Done

**Comment by ghedo** [comment]
Need to run `cargo +nightly fmt`. Also, I pushed https://github.com/cloudflare/quiche/commit/7eb0b085f20f6b39814eeb652bd1cb01d682b429 to shut clippy up, so please also rebase on master.
