### PR TITLE
Fix server app close before 1RTT never getting sent

### LINKED ISSUE #1118: Server stall if application close during handshake
I have created a couple test cases that shows what works and what breaks: 05e4618eb33c72f5912e26c0d851ad628452e0b7

From [10.2.3](https://datatracker.ietf.org/doc/html/rfc9000#section-10.2.3), I see that application errors must not be sent during the handshake due to that potentially leaking application information. Although the RFC seems to recommending dropping the application data and sending a 0x1c connection_close, I would prefer to pass that information back to the user.

Stepping through `send_single`, It looks like it stalls because `is_closed` causes no Handshake acks to be sent, and since the `pkt_type` is stays Handshake, an application close will not be sent.

What I expected was for the handshake to complete normally, and have the application close be sent with the first 1RTT short header packet ~along with HANDSHAKE_DONE~.

EDIT:
I implemented a possible change for this behavior: ffdaeed1b35e1810210071be80153187d15b8d2f

### PR DESCRIPTION
**Pull request by kevinjohna6**
If a server does an app close after a connection is established, but before it has actually emitted the Handshake ack, the close will not be sent.
This is because, per spec, app close error codes must not be sent during the Handshake, however the app error prevents the handshake acknowledgement from being emitted.

This patch's test case may give a better example of how this issue may occur.

The resulting behavior of this patch is that the Handshake ack packet will be sent followed by a 1RTT with the connection_close.

Resolves #1118

I have been using this patch for a while without experiencing side effects, but there may be a better way of mitigating this issue.

### CODE REVIEW

File: quiche/src/lib.rs [hunk 1]
```diff
@@ -12871,6 +12873,58 @@ mod tests {
...
+    fn app_close_by_server_during_handshake() {
+        let mut pipe = testing::Pipe::default().unwrap();
+
+        // Client sends initial flight.
+        let flight = testing::emit_flight(&mut pipe.client).unwrap();
+        testing::process_flight(&mut pipe.server, flight).unwrap();
+
+        let flight = testing::emit_flight(&mut pipe.server).unwrap();
+
+        // both are unestablished
```
Comment (ghedo) [inline quiche/src/lib.rs:12886]:
```suggestion
        // Both connections are not established.
```

File: quiche/src/lib.rs [hunk 2]
```diff
@@ -12871,6 +12873,58 @@ mod tests {
...
+        assert!(!pipe.client.is_established() && !pipe.server.is_established());
+
+        testing::process_flight(&mut pipe.client, flight).unwrap();
+
+        // connection established for client
```
Comment (ghedo) [inline quiche/src/lib.rs:12891]:
```suggestion
        // Connection is established on the client.
```

File: quiche/src/lib.rs [hunk 3]
```diff
@@ -12871,6 +12873,58 @@ mod tests {
...
+        assert!(pipe.client.is_established());
+        // send after established
```
Comment (ghedo) [inline quiche/src/lib.rs:12893]:
```suggestion

        // Client sends after connection is established.
```

File: quiche/src/lib.rs [hunk 4]
```diff
@@ -12871,6 +12873,58 @@ mod tests {
...
+        pipe.client.stream_send(0, b"badauthtoken", true).unwrap();
+
+        let flight = testing::emit_flight(&mut pipe.client).unwrap();
+        testing::process_flight(&mut pipe.server, flight).unwrap();
+
+        // connection established for server but the Handshake ack has not been
+        // sent yet
```
Comment (ghedo) [inline quiche/src/lib.rs:12900]:
```suggestion
```

File: quiche/src/lib.rs [hunk 5]
```diff
@@ -12871,6 +12873,58 @@ mod tests {
...
+        assert!(pipe.server.is_established());
+        // close after established
```
Comment (ghedo) [inline quiche/src/lib.rs:12902]:
```suggestion

        // Server closes after connection is established.
```

File: quiche/src/lib.rs [hunk 6]
```diff
@@ -12871,6 +12873,58 @@ mod tests {
...
+        pipe.server
+            .close(true, 123, b"Invalid authentication")
+            .unwrap();
+
+        // Server sends Handshake ack and then 1RTT connection_close
```
Comment (ghedo) [inline quiche/src/lib.rs:12907]:
```suggestion
        // Server sends Handshake ACK and then 1RTT CONNECTION_CLOSE.
```

**Review by ghedo — DISMISSED** [review]
LGTM, added some minor nits.

File: quiche/src/lib.rs [hunk 7]
```diff
@@ -12871,6 +12873,59 @@ mod tests {
...
+        // Connection is established on the client.
+        assert!(pipe.client.is_established());
+
+        // Client sends after connection is established.
+        pipe.client.stream_send(0, b"badauthtoken", true).unwrap();
+
+        let flight = testing::emit_flight(&mut pipe.client).unwrap();
+        testing::process_flight(&mut pipe.server, flight).unwrap();
+
+        // Connection is established on the server but the Handshake ACK is not sent.
```
Comment (ghedo) [inline quiche/src/lib.rs:12900]:
```suggestion
        // Connection is established on the server but the Handshake ACK has not
        // been sent yet.
```
